name: Delete Merged Branch

on:
  push:
    branches:
      - main
      - develop

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete merged branches
        run: |
          git fetch --prune
          for branch in $(git branch -r --merged | grep -vE 'main|develop|HEAD' | sed 's/origin\///'); do
            git push origin --delete $branch
          done