name: Delete Merged Branch

on:
  push:
    branches:
      - develop

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name 'Jojopok'
          git config --global user.email 'zaiajonathan@gmail.com'

      - name: Delete merged branches
        env:
          GITHUB_TOKEN: ${{ secrets.CALYPSO_TOKEN }}
        run: |
          git fetch --prune
          for branch in $(git branch -r --merged origin/develop | grep -vE 'develop|HEAD' | sed 's/origin\///'); do
            git push origin --delete $branch || echo "Failed to delete branch $branch"
          done